### ISSUE TITLE
Should run-vcpgk offer an explicit --clean-after-build option?

### ISSUE THREAD

**Issue by smkanadl** [lukka/CppBuildTasks#27]
I recently stumbled to build some libs (boost, ceres and qt-5-base) on a Microsoft hosted agent in DevOps due to insufficient disk space. It took me a while to figure out it was a disk space issue and then again some to to find out I can workaround by cleaning the buildtrees folder using the vcpkg option --clean-after-build.

I wasn't sure if it works if I just put it as last line into the pkg file, but it seems to do the trick.

```
boost-math:x64-linux
boost-test:x64-linux
boost-property-tree:x64-linux
ceres:x64-linux
qt5-base:x64-linux
--clean-after-build
```

I think it is woth to highlight this problem somewhere in the docs (Disk space limit is mentioned [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#capabilities-and-limitations)) and to extend the run-vcpkg task with an "clean" option which makes it easy to discover and set.

**Comment by lukka** [comment]
Right, an explicit task input `clean-after-build` is indeed useful.

A note about your solution: any flag stored in the response file could be as well passed explicitly on the command line to `vcpkg`, e.g. for the `run-vcpkg` task you could have put the same flag in the `vcpkgArguments` input. So there are two options here:
- adding the flag to the response file: this makes the flag part of the developer work, i.e. when the developer runs `vcpkg` to build the dependencies on the machine before building the app;
- adding the flag to the `vcpkgArguments` input in the yml file: this flag will be part of the CI build only, it will not affect the developer work on the development machine.

So yes, I just wanted to point out this little difference.

**Comment by smkanadl** [comment]
Good point. I was probably a bit desperate and was happy to get it working 🤣
