### ISSUE TITLE
task-vcpkg does not correctly detect need to bootstrap when vcpkg.exe is present

### ISSUE THREAD

**Issue by cbezault** [lukka/CppBuildTasks#29]
When using this task with a self-hosted agent which does not set `clean: True` in `checkout`, vcpkg is not re-bootstrapped. One could either bootstrap anytime the commit pointed to by the submodule changes or the output of `vcpkg version` can be compared to `toolsrc/VERSION.txt` for example.

[See this CI run.](https://dev.azure.com/vclibs/STL/_build/results?buildId=1203&view=logs&jobId=89e509dc-b698-550e-ac31-eaa041004158&j=89e509dc-b698-550e-ac31-eaa041004158&t=42c708a6-500c-57a5-8198-e4c7ee8c5a4f)

**Comment by lukka** [comment]
Yes, the `clean: True` scenario is not handled correctly by run-vcpkg task.
