### ISSUE TITLE
Run vcpkg task override cached installed folder

### ISSUE THREAD

**Issue by JamesYangLim** [lukka/CppBuildTasks#3]
**Issue:**

Using azure cache beta feature, I am able to cache ```$(Build.BinariesDirectory)/vcpkg/installed``` after I use vcpkg to install all the required packages. So in the following run, my pipeline restore ```$(Build.BinariesDirectory)/vcpkg/installed``` cache and then run the same vcpkg task again. 

**Expect**: Vcpkg will skip installing the packages as all of them have been restored.
**Actual**: Vcpkg re-install the packages again.

I realised that before I run vcpkg task, ```$(Build.BinariesDirectory)``` will be empty and running vcpkg task is doing a git checkout to vcpkg branch as shown in the flowchat. I suspect that git checkout override the restored ```$(Build.BinariesDirectory)/vcpkg/installed``` ? Any thoughts?

**Work around:**

I have to run vcpkg task before the cache restore with ```--dry-run``` argument, then run another vcpkg task to install the packages. This work fine, however both vcpkg run execute ```bootstrap-vcpkg.bat``` which took roughly 1.5 minutes each.

**Suggestion**

I think it will be good if there is a build vcpkg task that is seperated from run vcpkg. Hence the pipeline can be:

```git checkout vcpkg -> run bootstrap-vcpkg.bat -> restore cache -> vcpkg install packages```

This will give more control with the vcpkg task.

**Comment by lukka** [comment]
@JamesYangLim  thanks for the feedback! I am [working on a new version](https://dev.azure.com/CppBuild/CppBuildTasks/_build?definitionScope=%5CTests-Dev) of the vcpkg task with the fixes to correctly cache all the files (it currently ignores ".git", that is the reason everything gets rebuild again by vcpkg).

**Comment by JamesYangLim** [comment]
Thank you very much @lukka !

**Comment by lukka** [comment]
@JamesYangLim released new tasks with fixes related to caching vcpkg with CacheBeta task. Please try it out and let me know!

**Comment by JamesYangLim** [comment]
Thanks @lukka, it works really well.
