### ISSUE TITLE
How to pass arguments to cmake generator

### ISSUE THREAD

**Issue by ThadHouse** [lukka/CppBuildTasks#41]
It looks like theres a way to pass arguments as build time, but no way to pass arguments at generation time to run-cmake. Am I missing something obvious, or is this something that actually can't be done?

**Comment by lukka** [comment]
@ThadHouse  you can use the `cmakeAppendedArgs` input when using `CMakeListsTxtAdvanced `mode. Or you can specify any additional CMake argument in the CMakeSettings.json file.
